
cc_library(
    name="util",
    hdrs=[
        "util.hpp",
        "operators.hpp",
        "segfault_handler.hpp"
    ],
    deps = [
        "@boost",
        "@glog"
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name="include",
    hdrs=[
        "util.hpp",
        "operators.hpp"
    ],
    deps = [
        "@boost",
        "@glog"
    ],
    visibility = ["//visibility:public"],
)